USE dummydb;

SELECT *
FROM EMPLOYEES
WHERE FIRST_NAME = 'PETER';

SELECT *
FROM EMPLOYEES
WHERE EMPLOYEE_ID = 144;

SELECT *
FROM EMPLOYEES
WHERE SALARY < (SELECT SALARY
				FROM EMPLOYEES
				WHERE EMPLOYEE_ID = 144
				);
                
SELECT MAX(SALARY)
FROM EMPLOYEES;

-- HOW IS MAN HIGEST SALARY
SELECT *
FROM EMPLOYEES
WHERE SALARY  = (SELECT MAX(SALARY)
				FROM EMPLOYEES
                );

-- 2ND HIGEST SALARA
SELECT *
FROM EMPLOYEES
WHERE SALARY < (SELECT MAX(SALARY)
				FROM EMPLOYEES
                )
LIMIT 1;

SELECT *
FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20;

SELECT DEPARTMENT_ID
FROM DEPARTMENTS
WHERE DEPARTMENT_NAME = 'MARKETING';

SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
					FROM DEPARTMENTS
					WHERE DEPARTMENT_NAME = 'MARKETING'
					);
                    
SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
					FROM DEPARTMENTS
					WHERE DEPARTMENT_NAME = 'MARKETING'
					);

 -- IT DEPT A KOYJON EMPLOYEE ACA-- 
 
SELECT COUNT(EMPLOYEE_ID) AS MEMBERS
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID
					FROM DEPARTMENTS
					WHERE DEPARTMENT_NAME = 'IT'
					);

SELECT SUM(SALARY)
FROM EMPLOYEES
WHERE DEPARTMENT_ID = (SELECT JOB_ID
						FROM JOBS
                        WHERE JOB_TITLE ='PROGRAMMER');
 

SELECT SUM(SALARY) AS PRO_SALARY
FROM EMPLOYEES
WHERE JOB_ID = (SELECT JOB_ID
				FROM JOBS
                WHERE JOB_TITLE = 'PROGRAMMER');

SELECT * 
FROM JOBS;